services:
  fiotec-front:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_VERSAO_PLATAFORMA: "beta-2.5.x"
    environment:
      NEXT_PUBLIC_VERSAO_PLATAFORMA: "beta-2.5.x"
    ports:
      - "4000:4000"
    restart: unless-stopped

